#!/bin/bash

#Update hosts with given domain
read -p $'\e[1m\e[32mLocal Domain:\e[0m\e[39m ' localDomain
# TODO use sections in hosts file
#read -p $'\e[1m\e[32mHosts file section:\e[0m\e[39m ' section
echo "127.0.0.1		$localDomain" >> /etc/hosts
echo -e '- \e[1mHosts file updated for local loopback.'

# Create vhost file using template in current directory
echo -e '- \e[1mvhost file $localDomain.local created'

